### ISSUE TITLE
Bot will repeatedly quote the first issue when mentioning multiple issues

### ISSUE THREAD

**Issue by JayFoxRox** [citra-emu/discord-bot#3]
Reproduce using `Blah #1 #2 #3 #4 #5 #6 #7`

It will add a lot of spam with the same link (including preview) repeated 7 times (no special permissions / privileges necessary I believe?)

There should probably be a limit how often issues can be linked this way. Also the bot should list the actual issues mentioned / not just the first one over and over again.

**Comment by JayFoxRox** [comment]
I've just done this again and what happened earlier this week happened again: the bot did not only post 7 links, but 3x7 = 21!

I have no idea why this happens or if it's an issue with discord / discord client when too many links are sent at once. Eitherway, this has huge spamming potential.

**Comment by JayFoxRox** [comment]
This is not fixed. Bot always seems to repeat links 5 times

Also the bot won't respond to lines starting with the github ref number anymore. This is kind of annoying when someone asks something and you just want to link them to github really quick.

**Comment by chris062689** [comment]
Fixed by #8 and #9.
