### ISSUE TITLE
[RFC] Support for capping unique issues

### ISSUE THREAD

**Issue by anodium** [citra-emu/discord-bot#5]
Same way to reproduce as #3. Though #4 fixes duplicate issues, capping unique issues may require modifying config and other things, so we concluded it was out of scope.

Maybe concatenating all links into one message might also help with the spam? One notification with a handful of issues is much cleaner than a handful of notifications with one issue each. 🤔

**Comment by liushuyu** [comment]
No longer relevant, closing.
